### ISSUE TITLE
unable to install plugin

### ISSUE THREAD

**Issue by mitalib20** [spinscale/elasticsearch-ingest-opennlp#10]
I was trying to install this plugin on my windows system by using step which are described in readme file. after running the following command I got an error as shown in a screenshot. I am using elasticsearch 2.3.3 and java 7. Looking forward to your help. Thanks :)
![image](https://cloud.githubusercontent.com/assets/18072418/18306865/6ece75da-750b-11e6-8197-8169c04015f1.png)

**Comment by spinscale** [comment]
you need to specify a correct path. The `path/to/elasticsearch` was just a place holder. You need to build it locally and then use the locally build zip file to install.

Also, this plugin will not work with Elastic 2.3.3 only with latest 5.0 alpha version.

Please take your time and read the documentation instead of just trying out commands without the context around them.
